# Host binding "host:port"
host: "127.0.0.1:8003"

discord:
  # Bot Token
  token: 'NTU...0'
  # Channel ID for bot messages
  commands:
  - ban
  - unban
  - kick
  - grant
  - revoke
  - privs
  - status
  - msg
  help: "```css\n
        Support commands:\n
        !status, !ban, !unban, !kick, !grant, !revoke, !privs, !status, !msg```"

longPoll:
  connect:
    loggingEnabled: false
    maxLongpollTimeoutSeconds: 26
    maxEventBufferSize: 100
    eventTimeToLiveSeconds: 20
    deleteEventAfterFirstRetrieval: true

# Log level
#############
# Available log level: (panic, fatal, error, warning, info, debug)
loglevel: debug